import type { AIUsageModeSelection, MetricDefinition } from '../../domain/types/goalControl'
import { useGoalControlDashboard } from '../../hooks/useGoalControlDashboard'
import Button from '../ui/Button'
import QuestionBatch from '../ai/QuestionBatch'

const healthClass = { on_track: 'bg-emerald-100 text-emerald-900', attention: 'bg-amber-100 text-amber-900', at_risk: 'bg-red-100 text-red-900', paused: 'bg-slate-200 text-slate-700' }

export default function GoalControlDashboardPanel({ projectId }: { projectId: string }) {
  const { actualMinutes, addMetric, answerCheckIn, brief, busy, chatDraft, dashboard, error, messages, metricDrafts, patchPolicy, plannedMinutes, proposalSelections, resolveProposal, rollback, sendMessage, setBrief, setChatDraft, setMetricDrafts, toggleProposalDiff } = useGoalControlDashboard(projectId)

  if (!dashboard) return <section className="rounded-md border border-slate-200 p-4"><p className="text-sm text-slate-500">{busy ? 'Loading goal control dashboard…' : error || 'Dashboard unavailable.'}</p></section>

  const policyMode = (dashboard.policy.ai_usage_mode || 'inherit') as AIUsageModeSelection
  const completedActions = dashboard.actions.filter((action) => ['done', 'skipped'].includes(action.status)).length

  return (
    <div className="space-y-5 rounded-lg bg-slate-50 p-3 sm:p-5" data-testid="goal-control-dashboard">
      <section className="grid gap-3 md:grid-cols-4">
        <Kpi label="Goal health / 健康状态" value={dashboard.health.status.replace('_', ' ')} className={healthClass[dashboard.health.status]} />
        <Kpi label="Execution tier / 执行档位" value={dashboard.policy.active_tier} />
        <Kpi label="AI selected → effective" value={`${dashboard.usage.selected_mode} → ${dashboard.usage.effective_mode}`} />
        <Kpi label="Actions / 行动" value={`${completedActions} / ${dashboard.actions.length}`} />
      </section>

      <section className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
        <article className="rounded-md border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-950">Planning brief / 规划简报</h3><p className="mt-1 text-xs text-slate-500">Visible to you and included in compressed planning context.</p></div><Button disabled={busy} onClick={() => void patchPolicy({ planning_brief: { ...(dashboard.policy.planning_brief || {}), summary: brief } })}>Save brief</Button></div><textarea className="mt-3 min-h-28 w-full rounded-md border border-slate-300 p-3 text-sm leading-6" onChange={(event) => setBrief(event.target.value)} value={brief} /></article>
        <article className="space-y-3 rounded-md border border-slate-200 bg-white p-4"><h3 className="text-sm font-semibold text-slate-950">Control settings / 控制设置</h3><label className="block text-xs text-slate-600">AI usage mode<select className="mt-1 h-9 w-full rounded border border-slate-300 px-2 text-sm" onChange={(event) => void patchPolicy({ ai_usage_mode: event.target.value })} value={policyMode}><option value="inherit">Follow global / 跟随全局</option><option value="economy">Economy / 节省</option><option value="balanced">Balanced / 平衡</option><option value="quality">Quality / 质量优先</option></select></label><label className="block text-xs text-slate-600">Execution tier<select className="mt-1 h-9 w-full rounded border border-slate-300 px-2 text-sm" onChange={(event) => void patchPolicy({ active_tier: event.target.value })} value={dashboard.policy.active_tier}><option value="minimum">Minimum</option><option value="standard">Standard</option><option value="stretch">Stretch</option></select></label><p className="rounded bg-slate-50 p-2 text-xs text-slate-600">Administrator maximum: <strong>{dashboard.usage.administrator_maximum_mode}</strong>. Saved selections above it remain visible but are clamped at request time.</p></article>
      </section>

      <section className="rounded-md border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-950">Capacity / 容量</h3><p className="mt-1 text-xs text-slate-500">Calendar duration is not counted as actual effort.</p></div><p className="text-sm font-semibold text-slate-800">Planned {plannedMinutes} min · Actual {actualMinutes} min · Weekly capacity {dashboard.policy.weekly_capacity_minutes} min</p></div><div className="mt-3 h-3 overflow-hidden rounded bg-slate-100"><div className="h-full bg-emerald-600" style={{ width: `${Math.min(100, (plannedMinutes / Math.max(1, dashboard.policy.weekly_capacity_minutes)) * 100)}%` }} /></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{dashboard.health.factors.map((factor) => <div className="rounded bg-slate-50 p-2 text-xs" key={factor.key}><span className="block text-slate-500">{factor.label}</span><strong className="text-slate-900">{factor.value}</strong></div>)}</div></section>

      <section className="space-y-3"><div><h3 className="text-sm font-semibold text-slate-950">Metrics and trends / 指标趋势</h3><p className="text-xs text-slate-500">Low-confidence or anomalous values require confirmation before replanning.</p></div><div className="grid gap-3 lg:grid-cols-2">{dashboard.metrics.map((metric) => <article className="rounded-md border border-slate-200 bg-white p-3" key={metric.metric_id}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{metric.name}</p><p className="text-xs text-slate-500">{metric.role} · target {metric.target_value ?? '—'} {metric.unit}</p></div><MetricTrend metric={metric} /></div><div className="mt-3 flex gap-2"><input aria-label={`Record ${metric.name}`} className="h-9 min-w-0 flex-1 rounded border border-slate-300 px-2 text-sm" onChange={(event) => setMetricDrafts((current) => ({ ...current, [metric.metric_id]: event.target.value }))} type="number" value={metricDrafts[metric.metric_id] ?? ''} /><Button disabled={busy} onClick={() => void addMetric(metric)}>Record</Button></div></article>)}</div></section>

      <section className="rounded-md border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-sm font-semibold text-slate-950">Milestones and critical path / 里程碑与关键路径</h3><span className="rounded bg-red-50 px-2 py-1 text-xs text-red-700">Critical path: {dashboard.critical_path.total_minutes} min · projected {dashboard.critical_path.projected_finish || '—'}</span></div><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{dashboard.milestones.map((milestone, index) => { const prediction = (dashboard.milestone_predictions ?? []).find((item) => item.milestone_id === milestone.milestone_id); return <article className={`min-w-48 rounded-md border p-3 ${prediction?.at_risk ? 'border-red-200 bg-red-50' : 'border-slate-200'}`} key={milestone.milestone_id}><p className="text-xs text-slate-500">Milestone {index + 1}</p><p className="mt-1 text-sm font-semibold text-slate-900">{milestone.title}</p><p className="mt-2 text-xs text-slate-500">Due {milestone.due_date || '—'} · projected {prediction?.projected_finish || '—'} · {milestone.status}</p></article> })}</div></section>

      <section className="overflow-hidden rounded-md border border-slate-200 bg-white"><div className="border-b border-slate-200 p-4"><h3 className="text-sm font-semibold text-slate-950">Complete plan / 完整计划</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Action</th><th className="p-3">Tier</th><th className="p-3">Estimate</th><th className="p-3">Energy</th><th className="p-3">Due</th><th className="p-3">Status</th></tr></thead><tbody>{dashboard.actions.map((action) => <tr className={dashboard.critical_path.action_ids.includes(action.action_id) ? 'bg-red-50/50' : 'border-t border-slate-100'} key={action.action_id}><td className="p-3 font-medium text-slate-900">{action.title}{dashboard.critical_path.action_ids.includes(action.action_id) ? <span className="ml-2 text-[10px] text-red-700">critical</span> : null}</td><td className="p-3">{action.execution_tier}</td><td className="p-3">{action.estimated_minutes} min</td><td className="p-3">{String(action.energy_needed || 'medium')}</td><td className="p-3">{action.due_date || '—'}</td><td className="p-3">{action.status}</td></tr>)}</tbody></table></div></section>

      {dashboard.pending_check_in ? <section><h3 className="mb-2 text-sm font-semibold text-slate-950">Check-in inbox / Check-in 收件箱</h3><QuestionBatch disabled={busy} questions={dashboard.pending_check_in.questions} onSubmit={(answers) => answerCheckIn(dashboard.pending_check_in!.check_in_id, answers)} /></section> : null}

      <section className={`rounded-md border p-4 ${dashboard.review.recommend_replan ? 'border-amber-300 bg-amber-50' : 'border-slate-200 bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-950">Periodic review / 周期复盘</h3><p className="mt-1 text-xs text-slate-600">Deterministic medium-sensitivity rules; no plan is changed automatically.</p></div><span className="rounded bg-white px-2 py-1 text-xs font-medium text-slate-700">{dashboard.review.recommend_replan ? 'Adjustment suggested' : 'No adjustment trigger'}</span></div>{dashboard.review.triggers.length ? <ul className="mt-3 space-y-1 text-xs text-amber-900">{dashboard.review.triggers.map((item) => <li key={item.key}>• {item.label}</li>)}</ul> : <p className="mt-3 text-xs text-slate-500">Keep collecting Check-ins and measurements.</p>}{dashboard.review.safety_warnings.map((item) => <p className="mt-2 rounded bg-red-50 p-2 text-xs text-red-800" key={item.key}>{item.label} This warning can only suggest confirmation or a pause.</p>)}<p className="mt-3 text-xs font-medium text-slate-800">{dashboard.review.adjustment_question}</p></section>

      {(dashboard.proposals ?? []).filter((proposal) => proposal.status === 'pending').map((proposal) => <section className="rounded-md border border-violet-200 bg-violet-50 p-4" data-testid="plan-change-proposal" key={proposal.proposal_id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-violet-700">AI plan change proposal / AI 计划差异待审批</p><h3 className="mt-1 text-sm font-semibold text-slate-950">{proposal.reason || 'Suggested plan update'}</h3><p className="mt-1 text-xs text-slate-600">Nothing below changes the plan until you confirm it. Calendar drafts remain preview-only.</p>{proposal.proposal.capacityImpact ? <p className="mt-2 rounded bg-white px-2 py-1 text-xs text-slate-700">Capacity: {proposal.proposal.capacityImpact.before_minutes} → {proposal.proposal.capacityImpact.after_minutes} / {proposal.proposal.capacityImpact.available_minutes} buffered min · Calendar drafts: {proposal.proposal.calendarImpact?.draft_count ?? 0}</p> : null}</div><div className="flex gap-2"><Button disabled={busy} onClick={() => void resolveProposal(proposal.proposal_id, false)} variant="ghost">Reject</Button><Button disabled={busy || (proposal.diff.length > 0 && !(proposalSelections[proposal.proposal_id]?.length))} onClick={() => void resolveProposal(proposal.proposal_id, true)}>Accept selected</Button></div></div><div className="mt-3 grid gap-2 lg:grid-cols-2">{proposal.diff.map((item) => { const after = item.after || {}; const before = item.before || {}; const selected = proposalSelections[proposal.proposal_id]?.includes(item.id) ?? false; return <label className="flex cursor-pointer gap-3 rounded-md border border-violet-100 bg-white p-3 text-xs" key={item.id}><input checked={selected} className="mt-0.5" onChange={() => toggleProposalDiff(proposal.proposal_id, item.id)} type="checkbox" /><span><strong className="capitalize text-slate-900">{item.operation} {item.entity}: {String(after.title || before.title || item.external_id)}</strong><span className="mt-1 block text-slate-500">{item.operation === 'update' ? `${String(before.status || '—')} → ${String(after.status || '—')}` : String(after.description || 'New plan item')}</span></span></label> })}</div>{proposal.diff.length === 0 ? <p className="mt-3 rounded bg-white p-3 text-xs text-slate-600">This proposal only adds its attached progress note. It does not change Milestones or Actions.</p> : null}</section>)}

      <section className="grid gap-4 xl:grid-cols-2"><article className="rounded-md border border-slate-200 bg-white p-4"><h3 className="text-sm font-semibold text-slate-950">Plan versions / 计划版本</h3><div className="mt-3 max-h-64 space-y-2 overflow-auto">{dashboard.versions.map((version) => <div className="flex items-center justify-between gap-3 rounded bg-slate-50 p-2 text-xs" key={version.version_id}><div><strong>v{version.version_number}</strong> · {version.summary}<p className="text-slate-500">{version.source} · {version.created_at}</p></div><Button disabled={busy} onClick={() => { if (window.confirm('Create a new version by rolling back to this snapshot?')) void rollback(version.version_id) }} variant="ghost">Rollback</Button></div>)}</div></article><article className="flex min-h-72 flex-col rounded-md border border-slate-200 bg-white p-4"><h3 className="text-sm font-semibold text-slate-950">Goal conversation / 目标对话</h3><div className="mt-3 min-h-0 flex-1 space-y-2 overflow-auto">{messages.slice(-12).map((message) => <p className={`rounded p-2 text-xs ${message.role === 'user' ? 'ml-8 bg-slate-900 text-white' : 'mr-8 bg-slate-100 text-slate-700'}`} key={message.message_id}>{message.content}</p>)}</div><div className="mt-3 flex gap-2"><input className="h-9 min-w-0 flex-1 rounded border border-slate-300 px-2 text-sm" disabled={!dashboard.threads.length || busy} onChange={(event) => setChatDraft(event.target.value)} placeholder="Discuss or request a plan adjustment…" value={chatDraft} /><Button disabled={!chatDraft.trim() || busy} onClick={() => void sendMessage()}>Send</Button></div><p className="mt-2 text-[11px] text-slate-500">Messages are saved to the same goal thread. AI changes still require a separate difference proposal and confirmation.</p></article></section>
      {error ? <p className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}
    </div>
  )
}

function Kpi({ label, value, className = 'bg-white text-slate-900' }: { label: string; value: string; className?: string }) { return <article className={`rounded-md border border-slate-200 p-3 ${className}`}><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-lg font-semibold capitalize">{value}</p></article> }

function MetricTrend({ metric }: { metric: MetricDefinition }) {
  const values = metric.entries.map((entry) => entry.numeric_value).filter((value): value is number => typeof value === 'number')
  if (values.length < 2) return <span className="text-xs text-slate-400">Need 2 readings</span>
  const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(1, max - min)
  const points = values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 112 + 4},${36 - ((value - min) / range) * 28}`).join(' ')
  return <svg aria-label={`${metric.name} trend`} className="h-10 w-32" role="img" viewBox="0 0 120 40"><polyline fill="none" points={points} stroke="#047857" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" /></svg>
}
